image: ubuntu-latest

stages:
  - test

before_script:
  - npm install -g yarn
  - echo "::set-output name=dir::$(yarn cache dir)"

testing:
  stage: test
  script:
    - yarn
    - yarn lint
    - yarn test